ED-4000 feat: Github actions build job for upload art to  azure upload

diff --git a/.github/workflows/build-upload-artifact.yml b/.github/workflows/build-upload-artifact.yml
--- a/.github/workflows/build-upload-artifact.yml
+++ b/.github/workflows/build-upload-artifact.yml
@@ -3,10 +3,10 @@ name: Build and Upload Artifact
 on:
   push:
     branches:
-      - "*" # Trigger on push to the "deploy" branch
+      - "deploy" # Trigger on push to the "deploy" branch
   pull_request:
     branches:
-      - "*" # Trigger on pull request to the "deploy" branch
+      - "deploy" # Trigger on pull request to the "deploy" branch
 
 jobs:
   build_and_deploy:
@@ -23,7 +23,7 @@ jobs:
           node-version: "18.20.2" # Set up Node.js version 18
 
       - name: Customize dependencies
-        if: ${{ env.WL_Customization != null }} # Conditional step execution
+        if: ${{ github.event.inputs.WL_Customization != '' }} # Conditional step execution
         run: |
           git clone --recurse-submodules ${WL_Customization} sunbirded-portal # Clone repository with submodules
           cp -r sunbirded-portal/images/ src/app/client/src/assets # Copy images to client assets
@@ -37,7 +37,7 @@ jobs:
           commit_hash=$(git rev-parse --short HEAD) # Get commit hash
           build_tag=$(echo "${{ github.ref }}" | rev | cut -d/ -f1 | rev)_${commit_hash}_${GITHUB_RUN_NUMBER} # Generate build tag
           echo "build_tag=$build_tag" >> $GITHUB_ENV # Save build tag to environment variable
-          docker build -t myapp:${build_tag} . # Build Docker image
+          docker build -t myapp:$build_tag . # Build Docker image
         env:
           NODE_NAME: "18.20.2" # Set environment variable NODE_NAME
 
@@ -45,24 +45,35 @@ jobs:
         run: |
           docker save myapp:${{ env.build_tag }} -o myapp_${{ env.build_tag }}.tar # Save Docker image to a file
 
+      - name: Install Azure CLI
+        run: |
+          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+
+      - name: Create Azure Blob Storage Container
+        run: |
+          az storage container create \
+            --name my-container \
+            --account-name $AZURE_STORAGE_ACCOUNT \
+            --account-key $AZURE_STORAGE_KEY
+        env:
+          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
+          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
+
       - name: Upload to Azure Blob Storage
-        if: env.AZURE_STORAGE_ACCOUNT
-        uses: azure/CLI@v1
-        with:
-          inlineScript: |
-            az storage blob upload \
-              --account-name $AZURE_STORAGE_ACCOUNT \
-              --container-name my-container \
-              --file myapp_${{ env.build_tag }}.tar \
-              --name myapp_${{ env.build_tag }}.tar > upload_result.txt
-            upload_status=$?
-            if [ $upload_status -ne 0 ]; then
-              echo "Azure Blob Storage upload failed."
-              cat upload_result.txt
-              exit 1
-            else
-              echo "Azure Blob Storage upload succeeded."
-            fi
+        run: |
+          az storage blob upload \
+            --account-name $AZURE_STORAGE_ACCOUNT \
+            --container-name my-container \
+            --file myapp_${{ env.build_tag }}.tar \
+            --name myapp_${{ env.build_tag }}.tar > upload_result.txt
+          upload_status=$?
+          if [ $upload_status -ne 0 ]; then
+            echo "Azure Blob Storage upload failed."
+            cat upload_result.txt
+            exit 1
+          else
+            echo "Azure Blob Storage upload succeeded."
+          fi
         env:
           AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
           AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
